name: quiz_uts
description: A simple quiz app for UTS PM6

# Versi SDK minimal
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Package untuk state management
  provider: ^6.0.5

  # Tambahkan dependency lain jika perlu nanti
  # contoh: google_fonts, shared_preferences, dll

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Daftar folder asset
  assets:
    - assets/images/

  # Daftar font custom
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
